[package]
name = "surfer"
description = "A neat, minimal, opinionated windowing library for Nim."
version = "0.1.3"
license = "BSD3"
kind = "Library"
backend = "C"
binaries = []

[toolchain]
version = "2.2.0"

[dependencies]
pixie = ">= 5.1.0"
"gh:nim-windowing/linux_input" = ">= 0.1.0"
shakar = ">= 0.1.3"
xkb = ">= 1.4.1"
nayland = "== 0.1.4"
vmath = ">= 2.0.1"
chroma = ">= 1.0.0"

[platforms.native]
include = ["wayland-egl", "wayland-egl-backend", "glesv2", "egl"]
link = ["wayland-egl", "wayland-egl-backend", "glesv2", "egl"]
